const PRODUCT_TYPE = [
  {
    key: 'NAVBAR_CATEGORY_JEWELRY_AND_ACCESSORIES',
    name: 'JEWELRY_AND_ACCESSORIES',
    label: 'JEWELRY_AND_ACCESSORIES',
  },
  {
    key: 'NAVBAR_CATEGORY_CLOTHING_AND_SHOES',
    name: 'CLOTHING_AND_SHOES',
    label: 'CLOTHING_AND_SHOES',
  },
  {
    key: 'NAVBAR_CATEGORY_HOME_AND_LIVING',
    name: 'HOME_AND_LIVING',
    label: 'HOME_AND_LIVING',
  },
  {
    key: 'NAVBAR_CATEGORY_WEDDING_AND_PARTY',
    name: 'WEDDING_AND_PARTY',
    label: 'WEDDING_AND_PARTY',
  },
  {
    key: 'NAVBAR_CATEGORY_TOYS_AND_ENTERTAINMENT',
    name: 'TOYS_AND_ENTERTAINMENT',
    label: 'TOYS_AND_ENTERTAINMENT',
  },
  {
    key: 'NAVBAR_CATEGORY_ART_AND_COLLECTIBLES',
    name: 'ART_AND_COLLECTIBLES',
    label: 'ART_AND_COLLECTIBLES',
  },
];

export { PRODUCT_TYPE };
